<a href="https://colab.research.google.com/github/leonardo3108/ia025a/blob/main/Exercicios/ExercicioIntrodutorio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Curso Deep Learning - Exercício pré-curso Python - NumPy

Este é um notebook Jupyter contendo exercícios de programação matricial utilizando o Python e biblioteca NumPy.
Estes exercícios servem para verificar os conhecimentos da linguagem Python para manipulação matricial com a biblioteca NumPy.

Esta lista de exercício é um guia de estudo. Para fazer os exercícios será necessário estudar o Python e NumPy, consultar documentação e tutoriais disponíveis na Internet.

É um notebook que serve como guia de estudos também.

### Python

Estes exercícios devem ser feitos com o Python 3.
Recomenda-se utilizar o Google Colab para fazer esses exercícios (https://colab.research.google.com/)  ou instalar o Jupyter e o Python utilizando-se o [Anaconda](https://www.continuum.io/downloads) - uma distribuição focada em Data Science, contendo os principais pacotes usados nesta área.

### Jupyter notebook

Este é um Notebook Jupyter. Um notebook Jupyter é uma mistura de linguagem Markdown para formatar texto (como uma Wiki) e um programa Python. É muito usado entre as pessoas que trabalham com Data Science e Machine Learning em Python.

Se utilizar o Jupyter notebook, instale o Jupyter nbextensions que é um conjunto de ferramentas auxiliares. Habilite o "Table of Contents" do nbextensions para que este notebook fique itemizado. Para o Google Colab, não é possível instalar o nbextensions.

Você pode adicionar quantas células quiser neste notebook para deixar suas respostas bem organizadas.

# Exercícios básicos

Vamos começar! Comece imprimindo seu nome e e-mail aqui:

In [1]:
# preencha com seus dados
print('My name is Leonardo Pacheco')
print('My email is leonardo3108@gmail.com')

My name is Leonardo Pacheco
My email is leonardo3108@gmail.com


## Listas

Iremos utilizar muitas listas no curso Deep Learning.
Seguem alguns exercícios com lista. Python é muito bom para processar listas. Uma lista é uma sequência de elementos 
separados por vírgula dentro de chaves:

In [2]:
mylist = [5, 8, 'abc', 0, 8.3]

### Imprimindo o número de elementos de uma `mylist` e alguns de seus elementos. Veja como isso pode ser feito.

In [3]:
print(len(mylist))
print(mylist[0])
print(mylist[-1])  # observe o índice -1 (o que isso significa?)

5
5
8.3


## Seja uma lista de 10 elementos numéricos sequenciais, começando em zero

O código a seguir é típico para criar uma lista com os 10 primeiros inteiros maiores ou iguais a zero: inicializa-se lista vazia, para cada i entre 0 e menor que 10, faz append na lista a:

In [4]:
a = []
for i in range(10):
    a.append(i)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


## List Comprehension

Esta mesma lista pode ser criada utilizando a construção denominada "List Comprehension" ou
"Compreensão de Lista" em portugues. Coloque este termo no Google adicionando python na frente na forma:
"python comprehension list" e você poderá ver vários exemplos e tutoriais sobre o assunto. É uma forma compacta que fazer um append iterativo numa lista:

Veja como o trecho acima foi reduzido para uma linha apenas:

In [5]:
a = [i for i in range(10)]
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### Analise o trecho de programa a seguir:

In [6]:
m_list = ['r', 'i', 'c', 'a', 'r', 'd', 'o']
new_list = []
for k,item in enumerate(m_list):
    new_list.append(str(k) + item)
print(new_list)

['0r', '1i', '2c', '3a', '4r', '5d', '6o']


- Explique o que o enumerate faz no programa acima:

Explicação: permite obter cada índice da lista junto com o seu valor correspondente.

### Repita o mesmo trecho acima de criar a lista new_list, porém utilizando list comprehension:
   

In [8]:
m_list = ['r', 'i', 'c', 'a', 'r', 'd', 'o']
n_list = [str(k) + item for k,item in enumerate(m_list)] # utilize aqui o list comprehension
n_list

['0r', '1i', '2c', '3a', '4r', '5d', '6o']

## Fatiamento em Python

Um conceito fundamental em Python é o do fatiamento "slicing", em inglês. É um conceito que será muito usado
durante todo o curso. Estude bem isso. Inicialmente iremos trabalhar com fatiamento de lista, mas posteriormente
com arrays (ou tensores) utilizando o NumPy

In [9]:
print(a[3:5])

[3, 4]


### Veja como criar e imprimir uma lista a partir da lista "a" já criada, porém apenas alguns elementos

In [10]:
# imprima os elementos ímpares de a
print(a[1::2])
# imprima os elementos pares de a
print(a[::2])
# imprima os últimos 3 elementos da lista (utilize índice negativo, pesquise na Internet)
print(a[-3:])
# Imprima os 3 primeiros elementos da lista (veja quando é possível ignorar valores iniciais e finais)
print(a[:3])

[1, 3, 5, 7, 9]
[0, 2, 4, 6, 8]
[7, 8, 9]
[0, 1, 2]


### Veja o significado do passo, i.e. o terceiro parâmetro do "fatiamento":

In [11]:
print(a[::2])
print(a[::-1])

[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


### Exercício: Imprima os elementos ímpares na order reversa, do maior para o menor

In [12]:
print(a[::-2])

[9, 7, 5, 3, 1]


## Tuplas

Dominar o conceito de tuplas é importante pois tuplas são estruturas muito utilizadas no Python.

In [13]:
b = tuple(a)
print(b)

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


### Responda: A principal diferença entre uma lista e uma tupla é:

Resposta: a lista tem tamanho variável, a tupla tem tamanho fixo.

# Dicionários em Python

Python possui uma estrutura de dados muito versátil denominada dicionário.
No curso Deep Learning, os parâmetros da rede neural serão armazenadas na forma de dicionário. Veja a seguir alguns exemplos de uso de dicionários:

In [14]:
rob_record = {'nome': 'Roberto', 'idade': 18}
print(rob_record['nome'])

Roberto


In [15]:
rob_record['idade'] = 20
print(rob_record)

{'nome': 'Roberto', 'idade': 20}


Lista de dicionários:

In [16]:
records = [{'nome':'Alfredo', 'idade': 23},
           {'nome':'Fernanda', 'idade': 16},
           {'nome':'Carla', 'idade':33}]

### Exercício: Acesse o nome da Fernanda: complete e descomente a linha a seguir

In [17]:
print(records[1]['nome'])

Fernanda


### Exercício: crie uma lista com todos os nomes da lista records.

O resultado deve ser uma lista ['Alfredo', 'Fernanda', 'Carla']

In [18]:
# 1. Utilizando a forma tradicional de criar lista com append
# porém sem utilizar o for i in range()
nlist = []
for record in records:
  nlist.append(record['nome'])
print(nlist)

['Alfredo', 'Fernanda', 'Carla']


In [19]:
# 2. Utilizando a forma de list comprehension
nlist2 = [record['nome'] for record in records]
print(nlist2)

['Alfredo', 'Fernanda', 'Carla']


# Exercícios usando NumPy

Os seguintes exercícios devem usar apenas o pacote NumPy.
Não se deve utilizar nenhum outro pacote adicional.
O NumPy é o pacote que ter o Python apropriado para programação científica.
A programação eficiente de matrizes multidimensionais (arrays ou tensores) é
feita através do conceito de programação matricial que evita o uso de laços
e iterações nos elementos da matriz.

Existem vários exemplos de uso de NumPy no conjunto de
notebooks tutorias disponíveis no GitHub:
- https://github.com/robertoalotufo/ia898/blob/master/master/0_index.ipynb

In [20]:
import numpy as np

Veja como é possível criar um array unidimensional e depois reformatá-lo para ser acessado como array bidimensional:

In [21]:
array = np.arange(10)
print(array)
print(array.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [22]:
A = np.arange(24).reshape(4,6)
print(A)
print(A.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


### Exercício: imprimindo rows, cols, dimensions, shape and datatype

In [23]:
# imprima o número de linhas de A
print(len(A))
# imprima o número de colunas de A
print(A.shape[1])
# imprima o número de dimensões de A
print(len(A.shape))
# imprima o shape de A:
print(A.shape)
# imprima o tipo de dados (dtype) dos elementos de A:
print(A.dtype)

4
6
2
(4, 6)
int64


### Reshape

In [24]:
# Seja o vetor unidimension a:
a = np.array([1,2,3,4])
print(a, a.shape)

[1 2 3 4] (4,)


### Exercício: Converta o vetor unidimensional a em uma matriz vetor coluna (4 linhas e 1 coluna) utilizando reshape

In [25]:
a = a.reshape(4,1)
print(a)

[[1]
 [2]
 [3]
 [4]]


## Cópia por referência, cópia rasa e cópia profunda

Explique a diferença entre estes 3 tipos de cópias e dê um exemplo de cada uma.
**Resposta**:


In [26]:
# Exercício
# Indique para cada uma das expressões a seguir se a cópia é por referência, rasa ou profunda
x = a # cópia ? referência
y = a[:2] # cópia ? rasa
z = a.reshape(4,1) # cópia ? rasa 
zz = a.copy() # cópia ? profunda

In [27]:
# Explique o valor dos resultados:
z[0,0] = 5
print(a) # explique: alterou o elemento da primeira linha e coluna de z, que é igual ao primeiro elemento de a, pois a cópia é rasa (apenas referências)
y[1] = 6
print(a) # explique: alterou o segundo elemento de y, que é igual ao segundo elemento de a, pois a cópia é rasa (apenas referências)
x[2] = 8
print(a) # explique: alterou o terceiro elemento de "x", mas x é igual a "a", pois a cópia é por referência
zz[0] = 7
print(a) # explique: alterou o primeiro elemento de zz mas não alterou a, pois a cópia é profunda (valores, ao invés de referências)

[[5]
 [2]
 [3]
 [4]]
[[5]
 [6]
 [3]
 [4]]
[[5]
 [6]
 [8]
 [4]]
[[5]
 [6]
 [8]
 [4]]


## Operações aritméticas

In [28]:
B = A + 10
B

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33]])

### Array binário (booleano)

#### Exercício: Crie uma matriz booleana C com True nos elementos de B menores que 18 (não utilize loop explícito)

In [29]:
C = B < 18 # modify your code here
print(C)

[[ True  True  True  True  True  True]
 [ True  True False False False False]
 [False False False False False False]
 [False False False False False False]]


## Indexação booleana

### Exercício: explique o comando a seguir de indexação booleana

Explicação: B < 18 é uma matriz booleana, com 8 valores True e 16 valores false; A[B < 18] forma uma matriz unidimensional com os valores de A correspondentes aos índices dos valores True dessa matriz booleana.

In [30]:
A[B < 18]

array([0, 1, 2, 3, 4, 5, 6, 7])

Veja um programa que cria matriz D_loop a partir da matriz B, porém trocando os elementos menores que 18 por seus valores negativos

In [31]:
D_loop = B.copy()
for row in np.arange(B.shape[0]):
    for col in np.arange(B.shape[1]):
        if B[row,col] < 18:
            D_loop[row,col] = - B[row,col]
print(D_loop)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


### Exercício: Troque o corpo do laço do programa acima por uma única linha sem loop

In [32]:
D = B.copy()   # << modifique aqui utilizando indexação booleana
D[B < 18] = -B[B < 18]
print(D)

[[-10 -11 -12 -13 -14 -15]
 [-16 -17  18  19  20  21]
 [ 22  23  24  25  26  27]
 [ 28  29  30  31  32  33]]


## Redução de eixo: soma

Operações matriciais de redução de eixo são muito úteis e importantes.
É um conceito importante da programação matricial.

Estude o exemplo a seguir:

In [33]:
print(A)
print(A.shape)
As = A.sum(axis=0)
print(As)
print(As.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
[36 40 44 48 52 56]
(6,)


### Exercício: Explique o funcionamento da soma por redução de eixo. Qual foi a dimensão que desapareceu?

Resposta: Sumiu a dimensão das linhas, axis = 0, exatamente o que foi especificado no comando sum. Para isso, substituiu, para cada coluna, os 4 elementos das 4 linhas pela soma desses 4 elementos.

### Exercício: calcule o valor médio do array A

In [34]:
print(A.mean())

11.5


### Exercício: calcule o valor médio das linhas de A:

In [35]:
print(A.mean(axis=1))

[ 2.5  8.5 14.5 20.5]


## Broadcasting

### Exercício: O que significa o conceito de broadcasting em NumPy?

Resposta: é a adaptação de duas matrizes com tamanhos diferentes, quando compatíveis, replicando os valores da matriz menor (virtualmente) de modo a que ela fique exatamente com o mesmo tamanho da matriz maior.

In [36]:
# Usando o conceito de broadcast, mude o shape do vetor a para que o broadcast possa ocorrer em G = A + a
a = np.arange(4).reshape(4,1)
print(a)
G = A + a
print(G)

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 7  8  9 10 11 12]
 [14 15 16 17 18 19]
 [21 22 23 24 25 26]]


## Normalização entre 0 e 1

Seja a matriz $C$ que é a normalização da matriz $A$:
$$ C(i,j) = \frac{A(i,j) - A_{min}}{A_{max} - A_{min}} $$

Em programação matricial, não se faz o loop em cada elemento da matriz,
mas sim, utiliza-se operações matriciais. Faça o exercício a seguir
sem utilizar laços explícitos:

In [37]:
# Criar a matriz C que é a normalização de A, de modo que os valores de C estejam entre 0 e 1
C = (A - A.min()) / (A.max() - A.min())
print(C)

[[0.         0.04347826 0.08695652 0.13043478 0.17391304 0.2173913 ]
 [0.26086957 0.30434783 0.34782609 0.39130435 0.43478261 0.47826087]
 [0.52173913 0.56521739 0.60869565 0.65217391 0.69565217 0.73913043]
 [0.7826087  0.82608696 0.86956522 0.91304348 0.95652174 1.        ]]


In [38]:
# Modificar o exercício anterior, porém agora faça a normalização para cada coluna de A
# de modo que as colunas da matriz D estejam entre os valores de 0 a 1.
# Dica: utilize o conceito de redução de eixo
D = (A - A.min(axis=0)) / (A.max(axis=0) - A.min(axis=0))
print(D)

[[0.         0.         0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]
 [1.         1.         1.         1.         1.         1.        ]]


In [39]:
# Modificar o exercício anterior, porém agora faça a normalização para cada linha de A
# de modo que as *linhas* da matriz E estejam entre os valores de 0 a 1.
# Dica: utilize o conceito de redução de eixo, porém mantenha o mesmo número de eixos para poder fazer broadcast
E = (A - A.min(axis=1).reshape(4,1)) / (A.max(axis=1) - A.min(axis=1)).reshape(4,1)
print(E)

[[0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]]


## Fatiamento em arrays (slicing)

In [40]:
# esta indexação é chamada fatiamento:
AA = A[:,1::2]
print(AA)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]]


In [41]:
# criar a matriz AB apenas com as linhas pares da matriz A, utilizando o conceito de fatiamento:
print(A)
AB = A[::2,:]
print(AB)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]]


In [42]:
# crie a matriz AC com mesmo shape da matriz A, porém com os elementos na ordem inversa:
# trocando a ordem das linhas e das colunas
AC = A[::-1,::-1]
print(AC)

[[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


## Produto matricial  (dot product)

Calcule a matriz E dada pelo produto matricial entre a matriz A e sua transposta: 
$$ E = A A^T $$

In [43]:
E = np.dot(A, A.T) # modify your code here
print(E)

[[  55  145  235  325]
 [ 145  451  757 1063]
 [ 235  757 1279 1801]
 [ 325 1063 1801 2539]]


In [44]:
# Descomente a linha e explique
# por que a operação de multiplicação dá erro?
Ee = A * A.T

ValueError: ignored

**Resposta:** a multiplicação dot é elemento a elemento, para isso as matrizes precisam ter os mesmos tamanhos, ou ser possível o broadcast.

## Matrizes multidimensionais

Em deep learning, iremos utilizar matrizes multidimensionais
que são denominados como arrays no NumPy. PyTorch usa o nome de tensor para
suas matrizes multimensionais.

Matrizes de dimensões maior que 4 são de difícil intuição. A melhor forma de lidar
com elas é observando o seu *shape*.

### 3-D array

In [45]:
F = A.reshape(2,3,4)
print(F)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### Indexação

Estude as seguintes indexações:

In [46]:
F1 = F[1]
print(F1)
F2 = F[1,0,:]
print(F2)
F3 = F[1,0,2]
print(F3)
F4 = F[1:2,0,2]
print(F4)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[12 13 14 15]
14
[14]


In [47]:
print(F1.shape)
print(F2.shape)
print(F3.shape)
print(F4.shape)

(3, 4)
(4,)
()
(1,)


### Exercício: Explique as dimensões de cada array:

**F1:** fatia a segunda linha de F, removendo assim a primeira dimensão

**F2:** fatia a segunda linha e a primeira coluna de F, removendo assim a primeira e a segunda dimensões

**F3:** fatia a segunda linha e a primeira coluna e terceira profundidade de F, removendo assim todas as dimensões de F e chegando ao elemento pontual

**F4:** similar a F3, porém o fatiamento de linha não é por linha única mas por subconjuntos de linhas. Embora, a linha selecionada no fim é a mesma, a dimensão de linhas é preservada, sendo apenas reduzida de 2 para 1 linha

## Redução de eixo - aplicado a dois eixos simultâneos

Redução de eixo é quando a operação matricial resulta num array de menores dimensões.
Com essas operações, calcula-se estatística de colunas, linhas, etc.

### Exercício: Calcule o valor médio das matrizes F[0] e F[1], com apenas um mean no comando F.mean(??)

In [48]:
print(F.mean(axis=(1,2)))


[ 5.5 17.5]


## Function - split - dados treino e validação

O exercício a seguir é para separar um conjunto de dados (dataset) em dois conjuntos, um
de treinamento e outro de validação.


Defina uma função que receba como entrada uma matriz, (dataset), onde cada linha é
referente a uma amostra e cada coluna referente a um atributo das amostras. O número total de
amostras é dado pelas linhas desta matriz.
Outro parâmetro de entrada é o fator de split `split_factor`, que é um número real entre 0 e 1. 
A saída da função são duas matrizes: amostras de treinamento e amostras de validação. 
A matriz de treinamento contrá o número de linhas dado por `split_factor` vezes o número de amostras.
A matriz de validação conterá o restante das amostras.

In [53]:
# Entrada, matriz contendo 10 amostras e 9 atributos
aa = np.arange(90).reshape(10,9)
print(aa)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]
 [72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [54]:
# Saída da função t,v = split(aa, 0.8)  # utilizado split_factor de 80%
t = np.arange(72).reshape(8,9)
print(t)

[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42 43 44]
 [45 46 47 48 49 50 51 52 53]
 [54 55 56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69 70 71]]


In [55]:
v = np.arange(72,90).reshape(2,9)
print(v)

[[72 73 74 75 76 77 78 79 80]
 [81 82 83 84 85 86 87 88 89]]


In [82]:
# Evite o uso de laço explícito
# Não utilize outras bibliotecas além do NumPy
def split(dados, split_factor):
    '''
    divide a matriz dados em dois conjuntos:
    matriz train: split_factor * n. de linhas de dados
    matriz val: (1-split_factor) * n. de linhas de dados
    parametros entrada:
        dados: matriz de entrada
        split_factor: entre 0. e 1. - fator de divisão em duas matrizes
    parametros de saída:
        train : matriz com as linhas iniciais de dados
        val: matriz com as linhas restantes
    '''
    # insert your code here
    indexes = np.arange(len(aa))
    indexes_train = np.random.choice(indexes, int(split_factor * len(aa)), replace=False)
    indexes_val = np.setdiff1d(indexes, indexes_train)
    train = aa[indexes_train]
    val  =  aa[indexes_val]
    return train, val

t,v = split(aa, 0.8)
print('t=\n', t)
print('v=\n', v)

t=
 [[ 0  1  2  3  4  5  6  7  8]
 [63 64 65 66 67 68 69 70 71]
 [36 37 38 39 40 41 42 43 44]
 [ 9 10 11 12 13 14 15 16 17]
 [27 28 29 30 31 32 33 34 35]
 [72 73 74 75 76 77 78 79 80]
 [54 55 56 57 58 59 60 61 62]
 [81 82 83 84 85 86 87 88 89]]
v=
 [[18 19 20 21 22 23 24 25 26]
 [45 46 47 48 49 50 51 52 53]]


### Exercício: Teste sua função com outros valores

In [83]:
split(aa, 0.5)

(array([[72, 73, 74, 75, 76, 77, 78, 79, 80],
        [63, 64, 65, 66, 67, 68, 69, 70, 71],
        [54, 55, 56, 57, 58, 59, 60, 61, 62],
        [27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44]]),
 array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [45, 46, 47, 48, 49, 50, 51, 52, 53],
        [81, 82, 83, 84, 85, 86, 87, 88, 89]]))

# Programação Orientada a Objetos

Documentação oficial: https://docs.python.org/3/tutorial/classes.html

Forma clássica de definição de uma função:

In [84]:
data = np.array([13, 63, 5, 378, 58, 40])

def avg(d):
    return sum(d)/len(d)
    
avg(data)

92.83333333333333

## Definição da classe, variáveis, inicialização e método

Definição da classe `MyAvg`, contendo duas variávels: `id` (compartilhada) e `d`; inicialização e método `avg`.

- **Classe** é uma forma de definir um tipo abstrato de dados
- **Instância** de uma classe é chamada **objeto**
- Operadores ou funções de uma classe são chamados **métodos**
- **Variáveis de instância** são variáveis associadas à instância
- **Variáveis de classe** são variáveis compartilhada com todas as instâncias da classe

O nome de uma classe é usualmente escrita usando *Camel case* enquanto que métodos são
escritos com caixa baixa.

In [85]:
class MyAvg:
    id = 0.33                # variável compartilhada com todas as instâncias
    
    def __init__(self,data):
        self.d = data        # variável associada a cada instância 
        
    def avg(self): # método para calcular a média
        return sum(self.d)/len(self.d)

Objetos `a` e `b` são instâncias da classe `MyAvg`.
Instanciar uma classe é inicializá-la através da chamada ao método __init__:

In [86]:
a = MyAvg(data)
b = MyAvg(2*data)

Aplicação do método `avg()`, retorna a média dos dados dos objetos a e b:

In [87]:
print(a.avg())
print(b.avg())

92.83333333333333
185.66666666666666


In [89]:
# Imprima os valores dos dados associados aos objetos a e b:
print(a.d)
print(b.d)

[ 13  63   5 378  58  40]
[ 26 126  10 756 116  80]


In [90]:
# Imprima a variável compartilhada `id` de cada objeto a e b:
print(a.id)
print(b.id)

0.33
0.33


## Herança de classe

In [91]:
class MyAvgStd(MyAvg):
    def var(self): # método adicional para calcular a variância
        u = self.avg()
        return np.sqrt(np.sum((self.d - u)**2)/len(self.d))

In [92]:
c = MyAvgStd(data)

In [93]:
print('media:',c.avg())
print('variancia:',c.var())

media: 92.83333333333333
variancia: 129.294775180163


In [94]:
# imprima os dados associados ao objeto c e a sua variável compartilhada id
print(c.d)
print(c.id)

[ 13  63   5 378  58  40]
0.33


### Exercício: convertendo a função `split` na classe `C_Split`

Implemente a classe `C_Split` para ter a mesma funcionalidade da função `split` feita acima

In [95]:
class C_Split():
    def __init__(self,d):
        self.d = d
    def split(self, split_factor ):
        '''
        divide a matriz dados em dois conjuntos:
        matriz train: split_factor * n. de linhas de dados
        matriz val: (1-split_factor) * n. de linhas de dados
        parametros entrada:
            dados: matriz de entrada
            split_factor: entre 0. e 1. - fator de divisão em duas matrizes
        parametros de saída:
            train : matriz com as linhas iniciais de dados
            val: matriz com as linhas restantes
        '''
        # insert your code here
        indexes = np.arange(len(self.d))
        indexes_train = np.random.choice(indexes, int(split_factor * len(self.d)), replace=False)
        indexes_val = np.setdiff1d(indexes, indexes_train)
        train = self.d[indexes_train]
        val  =  self.d[indexes_val]
        return train, val

In [96]:
data_train_val = C_Split(aa)
train, val = data_train_val.split(0.8)

In [97]:
train, val

(array([[36, 37, 38, 39, 40, 41, 42, 43, 44],
        [81, 82, 83, 84, 85, 86, 87, 88, 89],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35],
        [72, 73, 74, 75, 76, 77, 78, 79, 80],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [63, 64, 65, 66, 67, 68, 69, 70, 71]]),
 array([[45, 46, 47, 48, 49, 50, 51, 52, 53],
        [54, 55, 56, 57, 58, 59, 60, 61, 62]]))

## Classe com métodos `__len__` e `__getitem__`

Uma classe com métodos `__len__` e `__getitem__` permite que os objetos possam ser indexados e calculado o seu número de elementos.

Veja o exemplo a seguir:

In [98]:
class Word():
    def __init__(self, phrase):
        self.wordlist = phrase.split() # separa frase em uma lista de palavras
    
    def __len__(self):
        return len(self.wordlist)
    
    def __getitem__(self,x):
        return self.wordlist[x]

In [99]:
frase = 'Esta frase é formada por 7 palavras'
palavras = Word(frase)

In [100]:
palavras[3]  # permite a indexação do objeto

'formada'

In [101]:
print(len(palavras))

7


### Exercício para indexar elementos de um dicionário

Um dicionário em Python não é indexado. Por exemplo seja o dicionário `d` a seguir.
Não é possível indexar d[0] ou d[1] para buscar o primeiro ou segundo par (chave:valor).

In [102]:
d = {'a':1,'b': 2}

Implementar uma classe que receba um dicionário e permita que ele possa ser indexado.
Para converter um dicionário em uma lista de pares, use:

In [103]:
list(d.items())

[('a', 1), ('b', 2)]

Complete a definição da classe `dicdata` a seguir para que um dicionário possa ser
indexado:

In [105]:
class DicData():
    def __init__(self, dic):
        self.dic = dic
        
    def __len__(self):
        return len(self.dic)
        
    def __getitem__(self, i):
        return list(self.dic.items())[i][0]

In [106]:
dd = DicData(d)
print(len(dd))
print(dd[0])

2
a


## Iteradores

Iteradores são uteis para serem usados em estruturas do tipo `for a in b:`.

Listas em Python são consideradas iteráveis, pois podem ser utilizadas nessa estrutura:

In [108]:
for i in ['a', 'b', 'c']:
    print(i)

a
b
c


O método do `range()` do python também é um iterável:

In [109]:
for i in range(3):
    print(i)

0
1
2


É possível acessar o iterador destas estruturas utilizando o método `iter()` do Python e então é possível percorrer seus elementos utilizado `next()`:

In [110]:
lista = ['a', 'b', 'c']
iterador = iter(lista)
print('tipo de iterador:', type(lista))
print('tipo de iterador:', type(iterador))
print(next(iterador))

tipo de iterador: <class 'list'>
tipo de iterador: <class 'list_iterator'>
a


O acesso de iteradores é sequencial e após o ultimo elemento uma exceção é levantada indicando o fim do iterador.
Descomente o último `next` e veja o tipo da exceção que acontece.

In [111]:
print(next(iterador))
print(next(iterador))
print(next(iterador))

b
c


StopIteration: ignored

## Criando objetos iteráveis

Para implementar um objeto iterador é preciso escrever um método `__next__()` para a classe e para que ele seja acessível como iterável também é necessário escrever um método `__iter__()`: 

In [112]:
class WordIterator():
    def __init__(self, phrase):
        self.words = phrase.split()
        
    def __iter__(self):
        self.iter_index = 0
        return self
    
    def __next__(self):
        if self.iter_index < len(self.words):
            i = self.iter_index
            self.iter_index += 1
            return self.words[i]
        else:
            raise StopIteration()

A classe acima é um iterador e é iterável. 

No método `__iter__()` reiniciamos o índice inicial para o iterador e retornamos o próprio objeto (um iterador).

No método `__next__()` retornamos a palavra do índice atual ou a exceção de parada, caso seja o fim.

In [113]:
frase = 'Esta frase é formada por 7 palavras'
iterador_de_palavras = WordIterator(frase)

In [114]:
for palavra in iterador_de_palavras:
    print(palavra)

Esta
frase
é
formada
por
7
palavras


### Exercício com iterador

Crie uma classe `DictIterator` que permita varrer os itens de um dicionário utilizando o `for`

In [124]:
class DictIterator():
    def __init__(self, dict):
        self.d = dict
        self.l = list(self.d.items())
    def __iter__(self):
        self.i = 0
        return self
    def __next__(self):
        if self.i < len(self.d):
            i = self.i
            self.i += 1
            return self.l[i]
        else:
            raise StopIteration()

In [125]:
d = {'a': 1,'b': 2, 'c': 3}
d_iter = DictIterator(d)
for i in d_iter:
    print(i)

('a', 1)
('b', 2)
('c', 3)


## Objeto como função

É possível declarar uma classe contendo um objeto possa ser chamado (*callable object*).
Para isso, a classe deve conter o método `__call__`. Veja o exemplo a seguir:

In [126]:
class Scale():
    def __init__(self, w):
        self._w = w
    def __call__(self, x):
        return x * self._w

In [127]:
s = Scale(100.)
print(s(5))


500.0


### Exercício de classe contendo objeto chamável

Defina uma classe herdada da classe `Scale` que permita modificar a variável `self._w`.

In [128]:
class AjustaPeso(Scale):
    def wset(self, w):
        self._w = w

In [129]:
ap = AjustaPeso(100.)
print(ap(5))

500.0


In [130]:
ap.wset(10)
print(ap(5))

50


# Fim do notebook